### ISSUE TITLE
'Accept-Encoding': '*' causes: Refused to set unsafe header "Accept-Encoding"

### ISSUE THREAD

**Issue by robertheessels** [nhost/nhost#1378]
**Describe the bug**
This commit:
https://github.com/nhost/nhost/commit/43646475016ae5f6e7982e7717a531a489ce56f7
Sets the header: `'Accept-Encoding': '*'`

It causes the browser to throw error:
`Refused to set unsafe header "Accept-Encoding"`

If you remove the line, all is fine.
And as it is last in the object spreads, there is even no way to overwrite it.

**To Reproduce**
Just call: `client.graphql.request(query)`

**Desktop (please complete the following information):**
OS: Mac
Browser: Chrome.

**Comment by elitan** [comment]
@robertheessels Maybe you can help us with a PR for this one? 🙏

**Comment by calvinlang** [comment]
I made a Pull Request here: [Removed accept headers \* in axios requests by calvinlang · Pull Request #1401 · nhost/nhost](https://github.com/nhost/nhost/pull/1401)

**Comment by RayZ0rG** [comment]
Just wondering when or if this fix has been released yet in new version of Nhost.  I am not exactly sure how to determine that.  Thanx.

**Comment by plmercereau** [comment]
Yes, the path has been released:
https://github.com/nhost/nhost/blob/main/packages/nhost-js/CHANGELOG.md

**Comment by yureckey** [comment]
I'm using "@nhost/vue": "1.13.2"
I see those errors when I'm doing graphql.request.
I even tried to call with { useAxios: false } but it is still the same (shows those errors tracked to Axios)
(I'm using nhost with Quasar)
